#!/bin/sh
#
# Copyright (C) 2013-2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh

board_config_update

json_is_a network object && exit 0

[ -d /sys/class/net/eth0 ] || exit 0

ucidef_set_interface_wan 'eth0'

for i in $(seq 10)
do
    [ -d /sys/class/net/eth${i} ] || break
    ucidef_set_interface_lan eth${i}
done

board_config_flush

exit 0
