#!/bin/sh

prereqs()
{
	true
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

# network mount, and vpn management commands
for cmd in $(cat /etc/initramfs-tools/hooks/walt-*.binaries)
do
    cmd_path="${DESTDIR}/sbin/${cmd}"
    if orig_cmd_path="$(which ${cmd})"
    then
        copy_exec "$orig_cmd_path" /sbin
    else
        cat > "$cmd_path" << EOF
#!/bin/sh
echo "Sorry, ${cmd} binary was not found on this system!" >&2
exit 1  # failed
EOF
        chmod +x "$cmd_path"
    fi
done

# modules needed
for mod in $(cat /etc/initramfs-tools/hooks/walt-*.modules)
do
    manual_add_modules $mod
done
